name: Integration Tests
on:
  workflow_dispatch

jobs:
  # Runs integration tests for each os
  run-integration-tests:
    name: Runs integration tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Run integration test
        shell: bash
        run: |
          cd cli/src/test/integration-tests-bash
          ./all-tests.sh
