name: MSI Builder
on: push

jobs:
  init_wixtoolset:
    runs-on: windows-latest
    steps:
      - name: Install Wix CLI
        run: |
          dotnet tool install --global wix --version 5.0.2
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: check
        run: dir
