name: MSI Builder
on: push

jobs:
  build-natives:
    name: Build native images
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21.0.2'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Build MSI for Windows
        run: |
          dotnet tool install --global wix --version 5.0.2
          wix extension list
          dotnet add package WixToolset.UI.wixext --version 5.0.2
          dotnet add package WixToolset.Util.wixext --version 5.0.2
          cd build-msi
          wix extension add WixToolset.UI.wixext
          wix extension add WixToolset.Util.wixext
          wix build Package.wxs WixUI_OwnSetup.wxs -loc Package.en-us.wxl -ext WixToolset.UI.wixext -ext WixToolset.Util.wixext -o ideasy.msi
          dir
          cd ..
          dir cli/target
        if: runner.os == 'Windows'
      - name: Upload native image
        uses: actions/upload-artifact@v4
        with:
          name: natives-${{ matrix.os }}
          path: cli/target/ideasy*
    
