name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test null bytes
        run: |
          if [ "$(git status -z)" = "" ]
          then
            echo "No changes, nothing to commit."
          else
            git add .
            git commit -m "Update urls"
            git push
          fi
