name: Test exec
on:
  push

jobs:
  # Downloads documentation docs artifact, builds all native images, archives native image for each os with documentation pdf file and uploads artifacts to f.e. natives-windows-latest
  build-natives:
    name: Build native images
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest, macos-13 ]
        #os: [ macos-latest ]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21.0.2'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Build native image
        shell: bash
        run: |
          cd cli
          mvn -B -ntp -Dideasy.assembly.id=${{ matrix.os }} -Pnative -DskipTests=true package
      - name: Upload native image
        uses: actions/upload-artifact@v4
        with:
          name: natives-${{ matrix.os }}
          path: cli/target/*.tar.gz
