name: Test exec
on:
  push

jobs:
  # Downloads documentation docs artifact, builds all native images, archives native image for each os with documentation pdf file and uploads artifacts to f.e. natives-windows-latest
  build-natives:
    name: Build native images
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ windows-latest, ubuntu-latest, macos-latest, macos-13 ]
        os: [ macos-latest ]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21.0.2'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Build native image
        shell: bash
        run: |
          cd cli
          mvn -B -ntp -Dideasy.assembly.id=${{ matrix.os }} -Pnative -DskipTests=true package
      - name: Upload native image
        uses: actions/upload-artifact@v4
        with:
          name: natives-${{ matrix.os }}
          path: cli/target/*.tar.gz

  # Downloads all native image artifacts to cli/target and builds the project for deployment to OSSRH Nexus
  deploy:
    name: Build Project and Deploy
    needs: [ build-natives ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Download natives and build project
        uses: actions/download-artifact@v4
        with:
          pattern: natives-*
          path: ./cli/target/
          merge-multiple: true
      - name: Configure Maven to use GitHub Packages
        run: |
          mkdir -p ~/.m2
          ls
          cp .mvn/settings.xml ~/.m2/settings.xml  
      - run: |
          mvn -B -ntp -Dstyle.color=always install
      - name: Deploy to GitHub Package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn --settings .mvn/settings.xml -DskipTests=true -Darchetype.test.skip=true -Dmaven.install.skip=true -Dgpg.skip=true -Dstyle.color=always -B -ntp deploy
