name: test
on:
  push

jobs:
  # Builds all native images and uploads each binary as a separate artifact
  build-natives:
    name: Build native images
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21.0.2'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Build native image
        shell: bash
        run: |
          maven_config="$(cat .mvn/maven.config)"
          current_version="${maven_config/#*-Drevision=}"
          current_version="${current_version/ */}"
          current_version="${current_version/-SNAPSHOT/-$(date +%m_%d_%H)-SNAPSHOT}"
          cd cli
          mvn -B -ntp -Pnative -DskipTests=true -Drevision=${current_version} package
      - name: Upload native image
        uses: actions/upload-artifact@v4
        with:
          name: natives-${{ matrix.os }}
          path: cli/target/ideasy*
